### PR TITLE
Changed the references to DeepSlice

### PR DESCRIPTION
**Pull request by PolarBean**
I corrected the references to DeepSlice so that they are consistent with the naming style in the main repository :)

### CODE REVIEW

**Comment by ThermoDev** [comment]
I'm not comfortable with the idea of displaying "DeepSlice" to the user. I believe it should show a space separated string to the user. I think we should revert the h1 and title to be Deep Slice. Please reply with what you best believe we should do moving forward.

**Comment by PolarBean** [comment]
hahaha the name of the package is DeepSlice, as are all the current references to it. It would be more confusing if we had two seperate names. Please refer to https://github.com/DeepLabCut/DeepLabCut for examples of this naming convention shown to users. 

Moving forward we should hang out soon.

**Comment by ThermoDev** [comment]
Hmmm, it seems that they have multiple conventions, one named DeepLabCut and another that's called DLC. Which naming convention are we using? They also do not have any examples of showing their products in an accessible way to the end user which is something we're doing. I'm worried that it will be detrimental of the UI/UX of the site. It will also have various effects on SEO, which is visible currently when you search Deep Slice. Iff you have taken this into consideration, and still believe it's best to move forward with this rename, then I'd be willing to accept this naming change. We have to ensure that this is the name we are going to stick with, and that no inconsistencies from naming will occur in the future, because not only will it hurt our brand, more importantly, it will hurt our leadership strategy and tactics by Jocko Willink.

**Comment by PolarBean** [comment]
haha I know you're trolling but you raise a good point. let this be the final name change, and how about instead of DeepSlice App as is visible when searching Deep Slice on google we change it to "DeepSlice Online". I'm keen to hear your opinion on this :) and what you think Jocko Willink would want us to do.

**Comment by ThermoDev** [comment]
I think Jocko Willink would want us to do exactly what we're doing, going over the plan, finding any inconsistencies, so that we can execute the mission. I also think DeepSlice Online sounds like a free mmo, so it should just be called DeepSlice, keep it consistent everywhere where we keep it as a single product. Feel free to add that in and I'll accept the PR. Or come up with a more effective name for the title, choice is yours.

**Pull request merged**
